export const FETCH_ALL_TRANSACTIONS_PENDING = "FETCH_ALL_TRANSACTIONS_PENDING";
export const FETCH_ALL_TRANSACTIONS_SUCCESS = "FETCH_ALL_TRANSACTIONS_SUCCESS";
export const FETCH_ALL_TRANSACTIONS_FAILED = "FETCH_ALL_TRANSACTIONS_FAILED";

export const ADD_NEW_TRANSACTION_PENDING = "ADD_NEW_TRANSACTION_PENDING";
export const ADD_NEW_TRANSACTION_SUCCESS = "ADD_NEW_TRANSACTION_SUCCESS";
export const ADD_NEW_TRANSACTION_FAILED = "ADD_NEW_TRANSACTION_FAILED";

export const DELETE_TRANSACTION_PENDING = "DELETE_TRANSACTION_PENDING";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILED = "DELETE_TRANSACTION_FAILED";

export const UPDATE_TRANSACTION_PENDING = "UPDATE_TRANSACTION_PENDING";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAILED = "UPDATE_TRANSACTION_FAILED";
