export const FETCH_ALL_CUSTOMERS_PENDING = "FETCH_ALL_CUSTOMERS_PENDING";
export const FETCH_ALL_CUSTOMERS_SUCCESS = "FETCH_ALL_CUSTOMERS_SUCCESS";
export const FETCH_ALL_CUSTOMERS_FAILED = "FETCH_ALL_CUSTOMERS_FAILED";

export const ADD_NEW_CUSTOMER_PENDING = "ADD_NEW_CUSTOMER_PENDING";
export const ADD_NEW_CUSTOMER_SUCCESS = "ADD_NEW_CUSTOMER_SUCCESS";
export const ADD_NEW_CUSTOMER_FAILED = "ADD_NEW_CUSTOMER_FAILED";

export const DELETE_CUSTOMER_PENDING = "DELETE_CUSTOMER_PENDING";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILED = "DELETE_CUSTOMER_FAILED";

export const UPDATE_CUSTOMER_PENDING = "UPDATE_CUSTOMER_PENDING";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILED = "UPDATE_CUSTOMER_FAILED";
