export const FETCH_ALL_MOVIES_PENDING = "FETCH_ALL_MOVIES_PENDING";
export const FETCH_ALL_MOVIES_SUCCESS = "FETCH_ALL_MOVIES_SUCCESS";
export const FETCH_ALL_MOVIES_FAILED = "FETCH_ALL_MOVIES_FAILED";

export const ADD_NEW_MOVIE_PENDING = "ADD_NEW_MOVIE_PENDING";
export const ADD_NEW_MOVIE_SUCCESS = "ADD_NEW_MOVIE_SUCCESS";
export const ADD_NEW_MOVIE_FAILED = "ADD_NEW_MOVIE_FAILED";

export const DELETE_MOVIE_PENDING = "DELETE_MOVIE_PENDING";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILED = "DELETE_MOVIE_FAILED";

export const UPDATE_MOVIE_PENDING = "UPDATE_MOVIE_PENDING";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAILED = "UPDATE_MOVIE_FAILED";
